name: test-vaultwarden-ldap

volumes:
  vaultwarden-data:
  openldap-data:

services:
  ldap:
    image: bitnami/openldap:2.6
    restart: unless-stopped
    networks:
      default:
        aliases:
          - openldap-container
    ports:
      - "389:389"
    volumes:
      - type: bind
        source: ./assets/ldap/ldifs
        target: /ldifs
        read_only: true
        bind:
          create_host_path: false
      - type: volume
        source: openldap-data
        target: /bitnami/openldap
    environment:
      - TZ=Asia/Tokyo
      - LDAP_PORT_NUMBER=389
      - LDAP_ROOT=dc=myserver,o=home
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin-pass
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=config-admin
      - LDAP_CONFIG_ADMIN_PASSWORD=config-admin-pass
      - LDAP_CUSTOM_LDIF_DIR=/ldifs

  app:
    image: vaultwarden/server:1.34.3
    restart: unless-stopped
    networks:
      default:
        aliases:
          - vaultwarden-container
    ports:
      - "8180:80"
    volumes:
      - type: volume
        source: vaultwarden-data
        target: /data
    environment:
      - TZ=Asia/Tokyo
      - DOMAIN=http://localhost:8180
      - INVITATIONS_ALLOWED=true
      - SIGNUPS_ALLOWED=true
      # ADMIN_TOKEN=admin-pass
      - ADMIN_TOKEN=$$argon2id$$v=19$$m=65540,t=3,p=4$$usxm21N0w4LWKCXIbfB8MUW7nChwXu8oUAWcNcF/C1w$$r2xZQyHQLvHaI0NUFaJFgts4TkWlXMq5pv8OcIa1WmU
    healthcheck:
      test: curl -f -s http://localhost:80 || exit 1
      start_period: 300s
      start_interval: 3s
      timeout: 5s
      interval: 300s
      retries: 3

  importer:
    image: ghcr.io/toras9000/vaultwarden-ldap-import:0.1.0
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./assets/vwli
        target: /vwli
        read_only: true
        bind:
          create_host_path: false
    environment:
      - TZ=Asia/Tokyo
      - VWLI_SETTINGS_FILE=/vwli/settings.json

  confirmer:
    image: ghcr.io/toras9000/vaultwarden-auto-confirm:0.1.0
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./assets/vwac
        target: /vwac
        read_only: true
        bind:
          create_host_path: false
    environment:
      - TZ=Asia/Tokyo
      - VWAC_SETTINGS_FILE=/vwac/settings.json
